on:
  push:
    branches:
      - adf_publish
name: AzureARMSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: azure/arm-deploy@v2
      with:
        resourceGroupName: rg-aaron-prd
        template: ./adf-aaron-devqa/ARMTemplateForFactory.json
        parameters: ./adf-aaron-devqa/ARMTemplateParametersForFactory.json
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
